import 'package:billkeep/utils/app_enums.dart';
import 'package:drift/drift.dart';
import 'package:billkeep/database/database.dart';

class DefaultWalletProviders {
  // List of default financial providers with their details
  static final List<Map<String, dynamic>> walletProviders = [
    // ==================== TRADITIONAL BANKS (US) ====================
    {
      'id': 'provider_chase',
      'name': 'Chase Bank',
      'description': 'One of the largest banks in the United States',
      'imageUrl': 'https://logo.clearbit.com/chase.com',
      'websiteUrl': 'https://www.chase.com',
      'isFiatBank': true,
      'isCrypto': false,
      'isMobileMoney': false,
      'isCreditCard': true,
      'countryISO2': 'US',
    },
    {
      'id': 'provider_bank_of_america',
      'name': 'Bank of America',
      'description': 'Major banking and financial services corporation',
      'imageUrl': 'https://logo.clearbit.com/bankofamerica.com',
      'websiteUrl': 'https://www.bankofamerica.com',
      'isFiatBank': true,
      'isCrypto': false,
      'isMobileMoney': false,
      'isCreditCard': true,
      'countryISO2': 'US',
    },
    {
      'id': 'provider_wells_fargo',
      'name': 'Wells Fargo',
      'description': 'Multinational financial services company',
      'imageUrl': 'https://logo.clearbit.com/wellsfargo.com',
      'websiteUrl': 'https://www.wellsfargo.com',
      'isFiatBank': true,
      'isCrypto': false,
      'isMobileMoney': false,
      'isCreditCard': true,
      'countryISO2': 'US',
    },
    {
      'id': 'provider_citibank',
      'name': 'Citibank',
      'description': 'Global banking and financial services',
      'imageUrl': 'https://logo.clearbit.com/citi.com',
      'websiteUrl': 'https://www.citi.com',
      'isFiatBank': true,
      'isCrypto': false,
      'isMobileMoney': false,
      'isCreditCard': true,
      'countryISO2': 'US',
    },
    {
      'id': 'provider_us_bank',
      'name': 'U.S. Bank',
      'description': 'American banking and financial services company',
      'imageUrl': 'https://logo.clearbit.com/usbank.com',
      'websiteUrl': 'https://www.usbank.com',
      'isFiatBank': true,
      'isCrypto': false,
      'isMobileMoney': false,
      'isCreditCard': true,
      'countryISO2': 'US',
    },
    {
      'id': 'provider_pnc',
      'name': 'PNC Bank',
      'description': 'Banking and financial services institution',
      'imageUrl': 'https://logo.clearbit.com/pnc.com',
      'websiteUrl': 'https://www.pnc.com',
      'isFiatBank': true,
      'isCrypto': false,
      'isMobileMoney': false,
      'isCreditCard': true,
      'countryISO2': 'US',
    },
    {
      'id': 'provider_td_bank',
      'name': 'TD Bank',
      'description': 'American national bank and financial services',
      'imageUrl': 'https://logo.clearbit.com/td.com',
      'websiteUrl': 'https://www.td.com',
      'isFiatBank': true,
      'isCrypto': false,
      'isMobileMoney': false,
      'isCreditCard': true,
      'countryISO2': 'US',
    },
    {
      'id': 'provider_capital_one',
      'name': 'Capital One',
      'description': 'Banking and credit card services',
      'imageUrl': 'https://logo.clearbit.com/capitalone.com',
      'websiteUrl': 'https://www.capitalone.com',
      'isFiatBank': true,
      'isCrypto': false,
      'isMobileMoney': false,
      'isCreditCard': true,
      'countryISO2': 'US',
    },
    {
      'id': 'provider_ally_bank',
      'name': 'Ally Bank',
      'description': 'Online-only bank with high-yield savings',
      'imageUrl': 'https://logo.clearbit.com/ally.com',
      'websiteUrl': 'https://www.ally.com',
      'isFiatBank': true,
      'isCrypto': false,
      'isMobileMoney': false,
      'isCreditCard': false,
      'countryISO2': 'US',
    },
    {
      'id': 'provider_chime',
      'name': 'Chime',
      'description': 'Mobile-first financial technology company',
      'imageUrl': 'https://logo.clearbit.com/chime.com',
      'websiteUrl': 'https://www.chime.com',
      'isFiatBank': true,
      'isCrypto': false,
      'isMobileMoney': true,
      'isCreditCard': false,
      'countryISO2': 'US',
    },
    {
      'id': 'provider_discover',
      'name': 'Discover Bank',
      'description': 'Digital banking and payment services',
      'imageUrl': 'https://logo.clearbit.com/discover.com',
      'websiteUrl': 'https://www.discover.com',
      'isFiatBank': true,
      'isCrypto': false,
      'isMobileMoney': false,
      'isCreditCard': true,
      'countryISO2': 'US',
    },

    // ==================== INTERNATIONAL BANKS ====================
    {
      'id': 'provider_hsbc',
      'name': 'HSBC',
      'description': 'Global banking and financial services',
      'imageUrl': 'https://logo.clearbit.com/hsbc.com',
      'websiteUrl': 'https://www.hsbc.com',
      'isFiatBank': true,
      'isCrypto': false,
      'isMobileMoney': false,
      'isCreditCard': true,
      'countryISO2': 'GB',
    },
    {
      'id': 'provider_barclays',
      'name': 'Barclays',
      'description': 'British multinational bank',
      'imageUrl': 'https://logo.clearbit.com/barclays.com',
      'websiteUrl': 'https://www.barclays.com',
      'isFiatBank': true,
      'isCrypto': false,
      'isMobileMoney': false,
      'isCreditCard': true,
      'countryISO2': 'GB',
    },
    {
      'id': 'provider_rbc',
      'name': 'RBC Royal Bank',
      'description': 'Canadian multinational financial services',
      'imageUrl': 'https://logo.clearbit.com/rbc.com',
      'websiteUrl': 'https://www.rbc.com',
      'isFiatBank': true,
      'isCrypto': false,
      'isMobileMoney': false,
      'isCreditCard': true,
      'countryISO2': 'CA',
    },
    {
      'id': 'provider_scotiabank',
      'name': 'Scotiabank',
      'description': 'Canadian multinational banking corporation',
      'imageUrl': 'https://logo.clearbit.com/scotiabank.com',
      'websiteUrl': 'https://www.scotiabank.com',
      'isFiatBank': true,
      'isCrypto': false,
      'isMobileMoney': false,
      'isCreditCard': true,
      'countryISO2': 'CA',
    },
    {
      'id': 'provider_deutsche_bank',
      'name': 'Deutsche Bank',
      'description': 'German multinational investment bank',
      'imageUrl': 'https://logo.clearbit.com/db.com',
      'websiteUrl': 'https://www.db.com',
      'isFiatBank': true,
      'isCrypto': false,
      'isMobileMoney': false,
      'isCreditCard': true,
      'countryISO2': 'DE',
    },
    {
      'id': 'provider_bnp_paribas',
      'name': 'BNP Paribas',
      'description': 'French international banking group',
      'imageUrl': 'https://logo.clearbit.com/bnpparibas.com',
      'websiteUrl': 'https://www.bnpparibas.com',
      'isFiatBank': true,
      'isCrypto': false,
      'isMobileMoney': false,
      'isCreditCard': true,
      'countryISO2': 'FR',
    },
    {
      'id': 'provider_credit_suisse',
      'name': 'Credit Suisse',
      'description': 'Swiss multinational investment bank',
      'imageUrl': 'https://logo.clearbit.com/credit-suisse.com',
      'websiteUrl': 'https://www.credit-suisse.com',
      'isFiatBank': true,
      'isCrypto': false,
      'isMobileMoney': false,
      'isCreditCard': true,
      'countryISO2': 'CH',
    },
    {
      'id': 'provider_santander',
      'name': 'Santander',
      'description': 'Spanish multinational financial services',
      'imageUrl': 'https://logo.clearbit.com/santander.com',
      'websiteUrl': 'https://www.santander.com',
      'isFiatBank': true,
      'isCrypto': false,
      'isMobileMoney': false,
      'isCreditCard': true,
      'countryISO2': 'ES',
    },

    // ==================== CREDIT CARD ISSUERS ====================
    {
      'id': 'provider_american_express',
      'name': 'American Express',
      'description': 'Premium credit card and financial services',
      'imageUrl': 'https://logo.clearbit.com/americanexpress.com',
      'websiteUrl': 'https://www.americanexpress.com',
      'isFiatBank': false,
      'isCrypto': false,
      'isMobileMoney': false,
      'isCreditCard': true,
      'countryISO2': 'US',
    },
    {
      'id': 'provider_visa',
      'name': 'Visa',
      'description': 'Global payments technology company',
      'imageUrl': 'https://logo.clearbit.com/visa.com',
      'websiteUrl': 'https://www.visa.com',
      'isFiatBank': false,
      'isCrypto': false,
      'isMobileMoney': false,
      'isCreditCard': true,
      'countryISO2': 'US',
    },
    {
      'id': 'provider_mastercard',
      'name': 'Mastercard',
      'description': 'Worldwide payment solutions and technology',
      'imageUrl': 'https://logo.clearbit.com/mastercard.com',
      'websiteUrl': 'https://www.mastercard.com',
      'isFiatBank': false,
      'isCrypto': false,
      'isMobileMoney': false,
      'isCreditCard': true,
      'countryISO2': 'US',
    },

    // ==================== MOBILE MONEY & DIGITAL WALLETS ====================
    {
      'id': 'provider_paypal',
      'name': 'PayPal',
      'description': 'Online payment and money transfer service',
      'imageUrl': 'https://logo.clearbit.com/paypal.com',
      'websiteUrl': 'https://www.paypal.com',
      'isFiatBank': false,
      'isCrypto': false,
      'isMobileMoney': true,
      'isCreditCard': false,
      'countryISO2': 'US',
    },
    {
      'id': 'provider_venmo',
      'name': 'Venmo',
      'description': 'Peer-to-peer mobile payment service',
      'imageUrl': 'https://logo.clearbit.com/venmo.com',
      'websiteUrl': 'https://venmo.com',
      'isFiatBank': false,
      'isCrypto': false,
      'isMobileMoney': true,
      'isCreditCard': false,
      'countryISO2': 'US',
    },
    {
      'id': 'provider_cash_app',
      'name': 'Cash App',
      'description': 'Mobile payment and investing platform',
      'imageUrl': 'https://logo.clearbit.com/cash.app',
      'websiteUrl': 'https://cash.app',
      'isFiatBank': false,
      'isCrypto': true,
      'isMobileMoney': true,
      'isCreditCard': false,
      'countryISO2': 'US',
    },
    {
      'id': 'provider_apple_pay',
      'name': 'Apple Pay',
      'description': 'Mobile payment and digital wallet by Apple',
      'imageUrl': 'https://logo.clearbit.com/apple.com',
      'websiteUrl': 'https://www.apple.com/apple-pay',
      'isFiatBank': false,
      'isCrypto': false,
      'isMobileMoney': true,
      'isCreditCard': false,
      'countryISO2': 'US',
    },
    {
      'id': 'provider_google_pay',
      'name': 'Google Pay',
      'description': 'Digital wallet and payment platform by Google',
      'imageUrl': 'https://logo.clearbit.com/google.com',
      'websiteUrl': 'https://pay.google.com',
      'isFiatBank': false,
      'isCrypto': false,
      'isMobileMoney': true,
      'isCreditCard': false,
      'countryISO2': 'US',
    },
    {
      'id': 'provider_samsung_pay',
      'name': 'Samsung Pay',
      'description': 'Mobile payment and digital wallet by Samsung',
      'imageUrl': 'https://logo.clearbit.com/samsung.com',
      'websiteUrl': 'https://www.samsung.com/us/samsung-pay',
      'isFiatBank': false,
      'isCrypto': false,
      'isMobileMoney': true,
      'isCreditCard': false,
      'countryISO2': 'KR',
    },
    {
      'id': 'provider_zelle',
      'name': 'Zelle',
      'description': 'Bank-to-bank money transfer service',
      'imageUrl': 'https://logo.clearbit.com/zellepay.com',
      'websiteUrl': 'https://www.zellepay.com',
      'isFiatBank': false,
      'isCrypto': false,
      'isMobileMoney': true,
      'isCreditCard': false,
      'countryISO2': 'US',
    },
    {
      'id': 'provider_mpesa',
      'name': 'M-Pesa',
      'description': 'Mobile money and payment service in Africa',
      'imageUrl': 'https://logo.clearbit.com/safaricom.co.ke',
      'websiteUrl': 'https://www.safaricom.co.ke/personal/m-pesa',
      'isFiatBank': false,
      'isCrypto': false,
      'isMobileMoney': true,
      'isCreditCard': false,
      'countryISO2': 'KE',
    },
    {
      'id': 'provider_mtn_momo',
      'name': 'MTN Mobile Money',
      'description': 'Mobile financial services in Africa',
      'imageUrl': 'https://logo.clearbit.com/mtn.com',
      'websiteUrl': 'https://www.mtn.com/what-we-do/mobile-financial-services',
      'isFiatBank': false,
      'isCrypto': false,
      'isMobileMoney': true,
      'isCreditCard': false,
      'countryISO2': 'ZA',
    },
    {
      'id': 'provider_alipay',
      'name': 'Alipay',
      'description': 'Chinese third-party mobile and online payment',
      'imageUrl': 'https://logo.clearbit.com/alipay.com',
      'websiteUrl': 'https://global.alipay.com',
      'isFiatBank': false,
      'isCrypto': false,
      'isMobileMoney': true,
      'isCreditCard': false,
      'countryISO2': 'CN',
    },
    {
      'id': 'provider_wechat_pay',
      'name': 'WeChat Pay',
      'description': 'Mobile payment platform by Tencent',
      'imageUrl': 'https://logo.clearbit.com/wechat.com',
      'websiteUrl': 'https://pay.weixin.qq.com',
      'isFiatBank': false,
      'isCrypto': false,
      'isMobileMoney': true,
      'isCreditCard': false,
      'countryISO2': 'CN',
    },
    {
      'id': 'provider_paytm',
      'name': 'Paytm',
      'description': 'Indian digital payment and financial services',
      'imageUrl': 'https://logo.clearbit.com/paytm.com',
      'websiteUrl': 'https://paytm.com',
      'isFiatBank': false,
      'isCrypto': false,
      'isMobileMoney': true,
      'isCreditCard': false,
      'countryISO2': 'IN',
    },
    {
      'id': 'provider_phonepe',
      'name': 'PhonePe',
      'description': 'Indian digital payments platform',
      'imageUrl': 'https://logo.clearbit.com/phonepe.com',
      'websiteUrl': 'https://www.phonepe.com',
      'isFiatBank': false,
      'isCrypto': false,
      'isMobileMoney': true,
      'isCreditCard': false,
      'countryISO2': 'IN',
    },
    {
      'id': 'provider_revolut',
      'name': 'Revolut',
      'description': 'Digital banking and financial technology',
      'imageUrl': 'https://logo.clearbit.com/revolut.com',
      'websiteUrl': 'https://www.revolut.com',
      'isFiatBank': true,
      'isCrypto': true,
      'isMobileMoney': true,
      'isCreditCard': true,
      'countryISO2': 'GB',
    },
    {
      'id': 'provider_wise',
      'name': 'Wise',
      'description': 'International money transfer service',
      'imageUrl': 'https://logo.clearbit.com/wise.com',
      'websiteUrl': 'https://wise.com',
      'isFiatBank': false,
      'isCrypto': false,
      'isMobileMoney': true,
      'isCreditCard': false,
      'countryISO2': 'GB',
    },
    {
      'id': 'provider_n26',
      'name': 'N26',
      'description': 'Digital mobile bank',
      'imageUrl': 'https://logo.clearbit.com/n26.com',
      'websiteUrl': 'https://n26.com',
      'isFiatBank': true,
      'isCrypto': false,
      'isMobileMoney': true,
      'isCreditCard': true,
      'countryISO2': 'DE',
    },
    {
      'id': 'provider_monzo',
      'name': 'Monzo',
      'description': 'Digital mobile-only bank',
      'imageUrl': 'https://logo.clearbit.com/monzo.com',
      'websiteUrl': 'https://monzo.com',
      'isFiatBank': true,
      'isCrypto': false,
      'isMobileMoney': true,
      'isCreditCard': false,
      'countryISO2': 'GB',
    },

    // ==================== CRYPTOCURRENCY PLATFORMS ====================
    {
      'id': 'provider_coinbase',
      'name': 'Coinbase',
      'description': 'Cryptocurrency exchange and wallet platform',
      'imageUrl': 'https://logo.clearbit.com/coinbase.com',
      'websiteUrl': 'https://www.coinbase.com',
      'isFiatBank': false,
      'isCrypto': true,
      'isMobileMoney': false,
      'isCreditCard': false,
      'countryISO2': 'US',
    },
    {
      'id': 'provider_binance',
      'name': 'Binance',
      'description': 'Global cryptocurrency exchange platform',
      'imageUrl': 'https://logo.clearbit.com/binance.com',
      'websiteUrl': 'https://www.binance.com',
      'isFiatBank': false,
      'isCrypto': true,
      'isMobileMoney': false,
      'isCreditCard': false,
      'countryISO2': null,
    },
    {
      'id': 'provider_kraken',
      'name': 'Kraken',
      'description': 'Cryptocurrency exchange and trading platform',
      'imageUrl': 'https://logo.clearbit.com/kraken.com',
      'websiteUrl': 'https://www.kraken.com',
      'isFiatBank': false,
      'isCrypto': true,
      'isMobileMoney': false,
      'isCreditCard': false,
      'countryISO2': 'US',
    },
    {
      'id': 'provider_gemini',
      'name': 'Gemini',
      'description': 'Regulated cryptocurrency exchange',
      'imageUrl': 'https://logo.clearbit.com/gemini.com',
      'websiteUrl': 'https://www.gemini.com',
      'isFiatBank': false,
      'isCrypto': true,
      'isMobileMoney': false,
      'isCreditCard': false,
      'countryISO2': 'US',
    },
    {
      'id': 'provider_crypto_com',
      'name': 'Crypto.com',
      'description': 'Cryptocurrency platform and Visa card',
      'imageUrl': 'https://logo.clearbit.com/crypto.com',
      'websiteUrl': 'https://crypto.com',
      'isFiatBank': false,
      'isCrypto': true,
      'isMobileMoney': false,
      'isCreditCard': true,
      'countryISO2': null,
    },
    {
      'id': 'provider_blockchain_com',
      'name': 'Blockchain.com',
      'description': 'Cryptocurrency wallet and exchange',
      'imageUrl': 'https://logo.clearbit.com/blockchain.com',
      'websiteUrl': 'https://www.blockchain.com',
      'isFiatBank': false,
      'isCrypto': true,
      'isMobileMoney': false,
      'isCreditCard': false,
      'countryISO2': null,
    },
    {
      'id': 'provider_metamask',
      'name': 'MetaMask',
      'description': 'Cryptocurrency wallet for Ethereum and tokens',
      'imageUrl': 'https://logo.clearbit.com/metamask.io',
      'websiteUrl': 'https://metamask.io',
      'isFiatBank': false,
      'isCrypto': true,
      'isMobileMoney': false,
      'isCreditCard': false,
      'countryISO2': null,
    },
    {
      'id': 'provider_trust_wallet',
      'name': 'Trust Wallet',
      'description': 'Multi-cryptocurrency mobile wallet',
      'imageUrl': 'https://logo.clearbit.com/trustwallet.com',
      'websiteUrl': 'https://trustwallet.com',
      'isFiatBank': false,
      'isCrypto': true,
      'isMobileMoney': false,
      'isCreditCard': false,
      'countryISO2': null,
    },
    {
      'id': 'provider_ledger',
      'name': 'Ledger',
      'description': 'Hardware cryptocurrency wallet',
      'imageUrl': 'https://logo.clearbit.com/ledger.com',
      'websiteUrl': 'https://www.ledger.com',
      'isFiatBank': false,
      'isCrypto': true,
      'isMobileMoney': false,
      'isCreditCard': false,
      'countryISO2': 'FR',
    },
    {
      'id': 'provider_trezor',
      'name': 'Trezor',
      'description': 'Hardware wallet for cryptocurrency',
      'imageUrl': 'https://logo.clearbit.com/trezor.io',
      'websiteUrl': 'https://trezor.io',
      'isFiatBank': false,
      'isCrypto': true,
      'isMobileMoney': false,
      'isCreditCard': false,
      'countryISO2': 'CZ',
    },
    {
      'id': 'provider_exodus',
      'name': 'Exodus',
      'description': 'Multi-cryptocurrency software wallet',
      'imageUrl': 'https://logo.clearbit.com/exodus.com',
      'websiteUrl': 'https://www.exodus.com',
      'isFiatBank': false,
      'isCrypto': true,
      'isMobileMoney': false,
      'isCreditCard': false,
      'countryISO2': 'US',
    },
    {
      'id': 'provider_bitpay',
      'name': 'BitPay',
      'description': 'Bitcoin and cryptocurrency payment processor',
      'imageUrl': 'https://logo.clearbit.com/bitpay.com',
      'websiteUrl': 'https://bitpay.com',
      'isFiatBank': false,
      'isCrypto': true,
      'isMobileMoney': false,
      'isCreditCard': true,
      'countryISO2': 'US',
    },

    // ==================== PAYMENT PROCESSORS ====================
    {
      'id': 'provider_stripe',
      'name': 'Stripe',
      'description': 'Online payment processing for businesses',
      'imageUrl': 'https://logo.clearbit.com/stripe.com',
      'websiteUrl': 'https://stripe.com',
      'isFiatBank': false,
      'isCrypto': false,
      'isMobileMoney': false,
      'isCreditCard': false,
      'countryISO2': 'US',
    },
    {
      'id': 'provider_square',
      'name': 'Square',
      'description': 'Payment and point of sale solutions',
      'imageUrl': 'https://logo.clearbit.com/squareup.com',
      'websiteUrl': 'https://squareup.com',
      'isFiatBank': false,
      'isCrypto': false,
      'isMobileMoney': false,
      'isCreditCard': false,
      'countryISO2': 'US',
    },
    {
      'id': 'provider_payoneer',
      'name': 'Payoneer',
      'description': 'Global payment and money transfer service',
      'imageUrl': 'https://logo.clearbit.com/payoneer.com',
      'websiteUrl': 'https://www.payoneer.com',
      'isFiatBank': false,
      'isCrypto': false,
      'isMobileMoney': true,
      'isCreditCard': true,
      'countryISO2': 'US',
    },
    {
      'id': 'provider_skrill',
      'name': 'Skrill',
      'description': 'Digital wallet and payment service',
      'imageUrl': 'https://logo.clearbit.com/skrill.com',
      'websiteUrl': 'https://www.skrill.com',
      'isFiatBank': false,
      'isCrypto': false,
      'isMobileMoney': true,
      'isCreditCard': false,
      'countryISO2': 'GB',
    },
    {
      'id': 'provider_neteller',
      'name': 'Neteller',
      'description': 'Online payment and money transfer',
      'imageUrl': 'https://logo.clearbit.com/neteller.com',
      'websiteUrl': 'https://www.neteller.com',
      'isFiatBank': false,
      'isCrypto': false,
      'isMobileMoney': true,
      'isCreditCard': true,
      'countryISO2': 'GB',
    },

    // ==================== AFRICAN MOBILE MONEY ====================
    {
      'id': 'provider_airtel_money',
      'name': 'Airtel Money',
      'description': 'Mobile money service in Africa and Asia',
      'imageUrl': 'https://logo.clearbit.com/airtel.com',
      'websiteUrl': 'https://www.airtel.in/bank',
      'isFiatBank': false,
      'isCrypto': false,
      'isMobileMoney': true,
      'isCreditCard': false,
      'countryISO2': 'IN',
    },
    {
      'id': 'provider_orange_money',
      'name': 'Orange Money',
      'description': 'Mobile payment service in Africa',
      'imageUrl': 'https://logo.clearbit.com/orange.com',
      'websiteUrl': 'https://www.orange.com/en/orange-money',
      'isFiatBank': false,
      'isCrypto': false,
      'isMobileMoney': true,
      'isCreditCard': false,
      'countryISO2': 'FR',
    },
    {
      'id': 'provider_tigo_pesa',
      'name': 'Tigo Pesa',
      'description': 'Mobile money service in Tanzania',
      'imageUrl': 'https://logo.clearbit.com/tigo.co.tz',
      'websiteUrl': 'https://www.tigo.co.tz',
      'isFiatBank': false,
      'isCrypto': false,
      'isMobileMoney': true,
      'isCreditCard': false,
      'countryISO2': 'TZ',
    },
    {
      'id': 'provider_ecocash',
      'name': 'EcoCash',
      'description': 'Mobile money service in Zimbabwe',
      'imageUrl': 'https://logo.clearbit.com/ecocash.co.zw',
      'websiteUrl': 'https://www.ecocash.co.zw',
      'isFiatBank': false,
      'isCrypto': false,
      'isMobileMoney': true,
      'isCreditCard': false,
      'countryISO2': 'ZW',
    },

    // ==================== INVESTMENT PLATFORMS ====================
    {
      'id': 'provider_robinhood',
      'name': 'Robinhood',
      'description': 'Commission-free investing and trading',
      'imageUrl': 'https://logo.clearbit.com/robinhood.com',
      'websiteUrl': 'https://robinhood.com',
      'isFiatBank': false,
      'isCrypto': true,
      'isMobileMoney': false,
      'isCreditCard': false,
      'countryISO2': 'US',
    },
    {
      'id': 'provider_webull',
      'name': 'Webull',
      'description': 'Commission-free stock and crypto trading',
      'imageUrl': 'https://logo.clearbit.com/webull.com',
      'websiteUrl': 'https://www.webull.com',
      'isFiatBank': false,
      'isCrypto': true,
      'isMobileMoney': false,
      'isCreditCard': false,
      'countryISO2': 'US',
    },
    {
      'id': 'provider_etoro',
      'name': 'eToro',
      'description': 'Social trading and investment platform',
      'imageUrl': 'https://logo.clearbit.com/etoro.com',
      'websiteUrl': 'https://www.etoro.com',
      'isFiatBank': false,
      'isCrypto': true,
      'isMobileMoney': false,
      'isCreditCard': false,
      'countryISO2': 'IL',
    },
  ];

  /// Seeds default providers into the database
  /// Only seeds if no providers exist yet
  static Future<void> seedDefaultProviders(AppDatabase database) async {
    // Check if providers already exist
    final existingProviders = await database
        .select(database.walletProviders)
        .get();
    if (existingProviders.isNotEmpty) {
      return; // Already seeded
    }

    // Insert all default providers
    for (final provider in walletProviders) {
      // Insert the provider
      await database
          .into(database.walletProviders)
          .insert(
            WalletProvidersCompanion(
              id: Value(provider['id'] as String),
              tempId: Value(provider['id'] as String),
              name: Value(provider['name'] as String),
              description: Value(provider['description'] as String?),
              imageUrl: Value(provider['imageUrl'] as String?),
              iconType: Value(IconSelectionType.image.name),
              websiteUrl: Value(provider['websiteUrl'] as String?),
              isFiatBank: Value(provider['isFiatBank'] as bool? ?? false),
              isCrypto: Value(provider['isCrypto'] as bool? ?? false),
              isMobileMoney: Value(provider['isMobileMoney'] as bool? ?? false),
              isCreditCard: Value(provider['isCreditCard'] as bool? ?? false),
              isDefault: const Value(true),
              isSynced: const Value(false),
            ),
          );

      // Insert countryISO2 as metadata if available
      if (provider['countryISO2'] != null) {
        await database
            .into(database.walletProviderMetadata)
            .insert(
              WalletProviderMetadataCompanion(
                providerId: Value(provider['id'] as String),
                key: const Value('countryISO2'),
                value: Value(provider['countryISO2'] as String),
                isSynced: const Value(false),
              ),
            );
      }
    }

    print('Seeded ${walletProviders.length} default providers into database');
  }
}
