import 'package:drift/drift.dart';
import 'package:billkeep/database/database.dart';

class DefaultCurrencies {
  // List of default currencies (fiat and crypto)
  static final List<Map<String, dynamic>> currencies = [
    // Major World Currencies
    {
      'code': 'USD',
      'name': 'US Dollar',
      'symbol': '\$',
      'decimals': 2,
      'isCrypto': false,
      'isActive': true,
    },
    {
      'code': 'EUR',
      'name': 'Euro',
      'symbol': '€',
      'decimals': 2,
      'isCrypto': false,
      'isActive': true,
    },
    {
      'code': 'GBP',
      'name': 'British Pound Sterling',
      'symbol': '£',
      'decimals': 2,
      'isCrypto': false,
      'isActive': true,
    },
    {
      'code': 'JPY',
      'name': 'Japanese Yen',
      'symbol': '¥',
      'decimals': 0,
      'isCrypto': false,
      'isActive': true,
    },
    {
      'code': 'CNY',
      'name': 'Chinese Yuan',
      'symbol': '¥',
      'decimals': 2,
      'isCrypto': false,
      'isActive': true,
    },
    {
      'code': 'CAD',
      'name': 'Canadian Dollar',
      'symbol': 'C\$',
      'decimals': 2,
      'isCrypto': false,
      'isActive': true,
    },
    {
      'code': 'AUD',
      'name': 'Australian Dollar',
      'symbol': 'A\$',
      'decimals': 2,
      'isCrypto': false,
      'isActive': true,
    },
    {
      'code': 'CHF',
      'name': 'Swiss Franc',
      'symbol': 'CHF',
      'decimals': 2,
      'isCrypto': false,
      'isActive': true,
    },
    {
      'code': 'NZD',
      'name': 'New Zealand Dollar',
      'symbol': 'NZ\$',
      'decimals': 2,
      'isCrypto': false,
      'isActive': true,
    },
    {
      'code': 'SEK',
      'name': 'Swedish Krona',
      'symbol': 'kr',
      'decimals': 2,
      'isCrypto': false,
      'isActive': true,
    },
    {
      'code': 'NOK',
      'name': 'Norwegian Krone',
      'symbol': 'kr',
      'decimals': 2,
      'isCrypto': false,
      'isActive': true,
    },
    {
      'code': 'DKK',
      'name': 'Danish Krone',
      'symbol': 'kr',
      'decimals': 2,
      'isCrypto': false,
      'isActive': true,
    },
    {
      'code': 'SGD',
      'name': 'Singapore Dollar',
      'symbol': 'S\$',
      'decimals': 2,
      'isCrypto': false,
      'isActive': true,
    },
    {
      'code': 'HKD',
      'name': 'Hong Kong Dollar',
      'symbol': 'HK\$',
      'decimals': 2,
      'isCrypto': false,
      'isActive': true,
    },

    // Other Major Currencies
    {
      'code': 'INR',
      'name': 'Indian Rupee',
      'symbol': '₹',
      'decimals': 2,
      'isCrypto': false,
      'isActive': true,
    },
    {
      'code': 'BRL',
      'name': 'Brazilian Real',
      'symbol': 'R\$',
      'decimals': 2,
      'isCrypto': false,
      'isActive': true,
    },
    {
      'code': 'RUB',
      'name': 'Russian Ruble',
      'symbol': '₽',
      'decimals': 2,
      'isCrypto': false,
      'isActive': true,
    },
    {
      'code': 'ZAR',
      'name': 'South African Rand',
      'symbol': 'R',
      'decimals': 2,
      'isCrypto': false,
      'isActive': true,
    },
    {
      'code': 'MXN',
      'name': 'Mexican Peso',
      'symbol': 'Mex\$',
      'decimals': 2,
      'isCrypto': false,
      'isActive': true,
    },
    {
      'code': 'KRW',
      'name': 'South Korean Won',
      'symbol': '₩',
      'decimals': 0,
      'isCrypto': false,
      'isActive': true,
    },
    {
      'code': 'TRY',
      'name': 'Turkish Lira',
      'symbol': '₺',
      'decimals': 2,
      'isCrypto': false,
      'isActive': true,
    },
    {
      'code': 'AED',
      'name': 'UAE Dirham',
      'symbol': 'د.إ',
      'decimals': 2,
      'isCrypto': false,
      'isActive': true,
    },
    {
      'code': 'SAR',
      'name': 'Saudi Riyal',
      'symbol': '﷼',
      'decimals': 2,
      'isCrypto': false,
      'isActive': true,
    },
    {
      'code': 'THB',
      'name': 'Thai Baht',
      'symbol': '฿',
      'decimals': 2,
      'isCrypto': false,
      'isActive': true,
    },
    {
      'code': 'MYR',
      'name': 'Malaysian Ringgit',
      'symbol': 'RM',
      'decimals': 2,
      'isCrypto': false,
      'isActive': true,
    },
    {
      'code': 'IDR',
      'name': 'Indonesian Rupiah',
      'symbol': 'Rp',
      'decimals': 0,
      'isCrypto': false,
      'isActive': true,
    },
    {
      'code': 'PHP',
      'name': 'Philippine Peso',
      'symbol': '₱',
      'decimals': 2,
      'isCrypto': false,
      'isActive': true,
    },
    {
      'code': 'VND',
      'name': 'Vietnamese Dong',
      'symbol': '₫',
      'decimals': 0,
      'isCrypto': false,
      'isActive': true,
    },
    {
      'code': 'PLN',
      'name': 'Polish Zloty',
      'symbol': 'zł',
      'decimals': 2,
      'isCrypto': false,
      'isActive': true,
    },
    {
      'code': 'CZK',
      'name': 'Czech Koruna',
      'symbol': 'Kč',
      'decimals': 2,
      'isCrypto': false,
      'isActive': true,
    },
    {
      'code': 'HUF',
      'name': 'Hungarian Forint',
      'symbol': 'Ft',
      'decimals': 0,
      'isCrypto': false,
      'isActive': true,
    },
    {
      'code': 'ILS',
      'name': 'Israeli New Shekel',
      'symbol': '₪',
      'decimals': 2,
      'isCrypto': false,
      'isActive': true,
    },
    {
      'code': 'EGP',
      'name': 'Egyptian Pound',
      'symbol': '£',
      'decimals': 2,
      'isCrypto': false,
      'isActive': true,
    },
    {
      'code': 'NGN',
      'name': 'Nigerian Naira',
      'symbol': '₦',
      'decimals': 2,
      'isCrypto': false,
      'isActive': true,
    },
    {
      'code': 'KES',
      'name': 'Kenyan Shilling',
      'symbol': 'KSh',
      'decimals': 2,
      'isCrypto': false,
      'isActive': true,
    },
    {
      'code': 'ARS',
      'name': 'Argentine Peso',
      'symbol': '\$',
      'decimals': 2,
      'isCrypto': false,
      'isActive': true,
    },
    {
      'code': 'CLP',
      'name': 'Chilean Peso',
      'symbol': '\$',
      'decimals': 0,
      'isCrypto': false,
      'isActive': true,
    },
    {
      'code': 'COP',
      'name': 'Colombian Peso',
      'symbol': '\$',
      'decimals': 0,
      'isCrypto': false,
      'isActive': true,
    },
    {
      'code': 'PEN',
      'name': 'Peruvian Sol',
      'symbol': 'S/',
      'decimals': 2,
      'isCrypto': false,
      'isActive': true,
    },
    {
      'code': 'GHS',
      'name': 'Ghanaian Cedi',
      'symbol': 'GH₵',
      'decimals': 2,
      'isCrypto': false,
      'isActive': true,
    },
    {
      'code': 'RWF',
      'name': 'Rwandan Franc',
      'symbol': 'FRw',
      'decimals': 0,
      'isCrypto': false,
      'isActive': true,
    },
    {
      'code': 'XOF',
      'name': 'West African CFA Franc',
      'symbol': 'CFA',
      'decimals': 0,
      'isCrypto': false,
      'isActive': true,
    },

    // Cryptocurrencies
    {
      'code': 'BTC',
      'name': 'Bitcoin',
      'symbol': '₿',
      'decimals': 8,
      'isCrypto': true,
      'isActive': true,
    },
    {
      'code': 'ETH',
      'name': 'Ethereum',
      'symbol': 'Ξ',
      'decimals': 18,
      'isCrypto': true,
      'isActive': true,
    },
    {
      'code': 'SOL',
      'name': 'Solana',
      'symbol': 'SOL',
      'decimals': 9,
      'isCrypto': true,
      'isActive': true,
    },
    {
      'code': 'BNB',
      'name': 'Binance Coin',
      'symbol': 'BNB',
      'decimals': 18,
      'isCrypto': true,
      'isActive': true,
    },
    {
      'code': 'XRP',
      'name': 'Ripple',
      'symbol': 'XRP',
      'decimals': 6,
      'isCrypto': true,
      'isActive': true,
    },
    {
      'code': 'ADA',
      'name': 'Cardano',
      'symbol': 'ADA',
      'decimals': 6,
      'isCrypto': true,
      'isActive': true,
    },
    {
      'code': 'DOGE',
      'name': 'Dogecoin',
      'symbol': 'Ð',
      'decimals': 8,
      'isCrypto': true,
      'isActive': true,
    },
    {
      'code': 'DOT',
      'name': 'Polkadot',
      'symbol': 'DOT',
      'decimals': 10,
      'isCrypto': true,
      'isActive': true,
    },
    {
      'code': 'MATIC',
      'name': 'Polygon',
      'symbol': 'MATIC',
      'decimals': 18,
      'isCrypto': true,
      'isActive': true,
    },
    {
      'code': 'AVAX',
      'name': 'Avalanche',
      'symbol': 'AVAX',
      'decimals': 18,
      'isCrypto': true,
      'isActive': true,
    },
    {
      'code': 'LINK',
      'name': 'Chainlink',
      'symbol': 'LINK',
      'decimals': 18,
      'isCrypto': true,
      'isActive': true,
    },
    {
      'code': 'UNI',
      'name': 'Uniswap',
      'symbol': 'UNI',
      'decimals': 18,
      'isCrypto': true,
      'isActive': true,
    },
    {
      'code': 'LTC',
      'name': 'Litecoin',
      'symbol': 'Ł',
      'decimals': 8,
      'isCrypto': true,
      'isActive': true,
    },
    {
      'code': 'TRX',
      'name': 'TRON',
      'symbol': 'TRX',
      'decimals': 6,
      'isCrypto': true,
      'isActive': true,
    },
    {
      'code': 'ATOM',
      'name': 'Cosmos',
      'symbol': 'ATOM',
      'decimals': 6,
      'isCrypto': true,
      'isActive': true,
    },
    {
      'code': 'XLM',
      'name': 'Stellar',
      'symbol': 'XLM',
      'decimals': 7,
      'isCrypto': true,
      'isActive': true,
    },
    {
      'code': 'XMR',
      'name': 'Monero',
      'symbol': 'XMR',
      'decimals': 12,
      'isCrypto': true,
      'isActive': true,
    },
    {
      'code': 'ALGO',
      'name': 'Algorand',
      'symbol': 'ALGO',
      'decimals': 6,
      'isCrypto': true,
      'isActive': true,
    },
    {
      'code': 'VET',
      'name': 'VeChain',
      'symbol': 'VET',
      'decimals': 18,
      'isCrypto': true,
      'isActive': true,
    },
    {
      'code': 'FIL',
      'name': 'Filecoin',
      'symbol': 'FIL',
      'decimals': 18,
      'isCrypto': true,
      'isActive': true,
    },

    // Stablecoins
    {
      'code': 'USDT',
      'name': 'Tether',
      'symbol': 'USDT',
      'decimals': 6,
      'isCrypto': true,
      'isActive': true,
    },
    {
      'code': 'USDC',
      'name': 'USD Coin',
      'symbol': 'USDC',
      'decimals': 6,
      'isCrypto': true,
      'isActive': true,
    },
    {
      'code': 'DAI',
      'name': 'Dai',
      'symbol': 'DAI',
      'decimals': 18,
      'isCrypto': true,
      'isActive': true,
    },
    {
      'code': 'BUSD',
      'name': 'Binance USD',
      'symbol': 'BUSD',
      'decimals': 18,
      'isCrypto': true,
      'isActive': true,
    },
  ];

  /// Seeds default currencies into the database
  /// Only seeds if no currencies exist yet
  static Future<void> seedDefaultCurrencies(AppDatabase database) async {
    // Check if currencies already exist
    final existingCurrencies = await database.select(database.currencies).get();
    if (existingCurrencies.isNotEmpty) {
      return; // Already seeded
    }

    // Insert all default currencies
    for (final currency in currencies) {
      await database.into(database.currencies).insert(
            CurrenciesCompanion(
              code: Value(currency['code'] as String),
              name: Value(currency['name'] as String),
              symbol: Value(currency['symbol'] as String),
              decimals: Value(currency['decimals'] as int),
              isCrypto: Value(currency['isCrypto'] as bool),
              isActive: Value(currency['isActive'] as bool),
            ),
          );
    }
  }
}
